
const eventsBase = [
    {
        id: 1,
        image: "/event1.jpg",
        cathegory: "Meeting",
        author: "Admin",
        date: "March 4 2021",
        title: "Vivamus hendrerit wisi ded non",
        text: "Morbi mauris nec massa quis ante. Morbi tincidunt. Maecenas eget volutpat quis, libero. Maecenas pellentesque eget, vestibulum tristique sem. Cras vitae erat augue, ullamcorper.",
    },
    {
        id: 2,
        image: "/event2.jpg",
        cathegory: "Recipes",
        author: "Admin",
        date: "March 6 2021",
        title: "Lorem ipsum dolor sit amet",
        text: "Morbi mauris nec massa quis ante. Morbi tincidunt. Maecenas eget volutpat quis, libero. Maecenas pellentesque eget, vestibulum tristique sem. Cras vitae erat augue, ullamcorper.",
    },
    {
        id: 3,
        image: "./event3.jpg",
        cathegory: "Live music",
        author: "Admin",
        date: "March 6 2021",
        title: "Sit amet consectetur adipisicing elit",
        text: "Morbi mauris nec massa quis ante. Morbi tincidunt. Maecenas eget volutpat quis, libero. Maecenas pellentesque eget, vestibulum tristique sem. Cras vitae erat augue, ullamcorper.",
    },
    {
        id: 4,
        image: "./event4.jpg",
        cathegory: "Stuff",
        author: "Admin",
        date: "March 9 2021",
        title: "Fuga eveniet dolor ab nihil",
        text: "Morbi mauris nec massa quis ante. Morbi tincidunt. Maecenas eget volutpat quis, libero. Maecenas pellentesque eget, vestibulum tristique sem. Cras vitae erat augue, ullamcorper.",
    },
    {
        id: 5,
        image: "./event5.jpg",
        cathegory: "Meeting",
        author: "Admin",
        date: "March 9 2021",
        title: "Vivamus hendrerit wisi ded non",
        text: "Morbi mauris nec massa quis ante. Morbi tincidunt. Maecenas eget volutpat quis, libero. Maecenas pellentesque eget, vestibulum tristique sem. Cras vitae erat augue, ullamcorper.",
    },
    {
        id: 6,
        image: "./event6.jpg",
        cathegory: "Recipes",
        author: "Admin",
        date: "March 11 2021",
        title: "Sit amet consectetur adipisicing elit",
        text: "Morbi mauris nec massa quis ante. Morbi tincidunt. Maecenas eget volutpat quis, libero. Maecenas pellentesque eget, vestibulum tristique sem. Cras vitae erat augue, ullamcorper.",
    },
    {
        id: 7,
        image: "./event7.jpg",
        cathegory: "Recipes",
        author: "Admin",
        date: "March 12 2021",
        title: "Fuga eveniet dolor ab nihil",
        text: "Morbi mauris nec massa quis ante. Morbi tincidunt. Maecenas eget volutpat quis, libero. Maecenas pellentesque eget, vestibulum tristique sem. Cras vitae erat augue, ullamcorper.",
    },
    {
        id: 8,
        image: "./event8.jpg",
        cathegory: "Stuff",
        author: "Admin",
        date: "March 14 2021",
        title: "Vivamus hendrerit wisi ded non",
        text: "Morbi mauris nec massa quis ante. Morbi tincidunt. Maecenas eget volutpat quis, libero. Maecenas pellentesque eget, vestibulum tristique sem. Cras vitae erat augue, ullamcorper.",
    },
]

export default eventsBase